--Criado por JuniorGBJ
--Atualizado para Shop Control v9.5.1.5
--Executar em S9_Real

ALTER INDEX ALL ON	Cli_For_Contatos	REBUILD
ALTER INDEX ALL ON	Campanhas_MobileView	REBUILD
ALTER INDEX ALL ON	Demais_Documentos_ECF	REBUILD
ALTER INDEX ALL ON	Compromissos_Agrupamento	REBUILD
ALTER INDEX ALL ON	Compromissos_Funcionarios	REBUILD
ALTER INDEX ALL ON	Parametros_Scanntech_Filiais	REBUILD
ALTER INDEX ALL ON	Resultados_Campanhas_MobileView	REBUILD
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_Referenciados	REBUILD
ALTER INDEX ALL ON	Configuracoes_Gerador_Relatorios	REBUILD
ALTER INDEX ALL ON	Financeiro_Cobranca_Passos_Historico	REBUILD
ALTER INDEX ALL ON	Movimento_Ordem_Producao	REBUILD
ALTER INDEX ALL ON	Recebimento_Nao_Fiscal_ECF	REBUILD
ALTER INDEX ALL ON	A_Fazer_Funcionarios	REBUILD
ALTER INDEX ALL ON	Sequencia_Operacao	REBUILD
ALTER INDEX ALL ON	Etiquetas_Pendentes	REBUILD
ALTER INDEX ALL ON	Grupos_Coleta	REBUILD
ALTER INDEX ALL ON	Funcionarios_Pastas_Mensagens	REBUILD
ALTER INDEX ALL ON	Movimento_PV	REBUILD
ALTER INDEX ALL ON	Parametros_Scanntech_Urls	REBUILD
ALTER INDEX ALL ON	Funcionarios_Operacoes_Bloqueadas_Entrada	REBUILD
ALTER INDEX ALL ON	Retorno_SAT	REBUILD
ALTER INDEX ALL ON	Compromissos_Agrupamento_Funcionarios	REBUILD
ALTER INDEX ALL ON	Movimento_Ordem_Producao_Comentarios	REBUILD
ALTER INDEX ALL ON	A_Fazer_Grupos	REBUILD
ALTER INDEX ALL ON	Motivo_Cancelamento_Orcamento	REBUILD
ALTER INDEX ALL ON	Scanntech_Movimento_Exportado	REBUILD
ALTER INDEX ALL ON	SAT_Compartilhado_Pedidos_Consulta	REBUILD
ALTER INDEX ALL ON	Cli_For_Credito_Lock	REBUILD
ALTER INDEX ALL ON	Noticia	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_Ordem_Producao	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_Lote	REBUILD
ALTER INDEX ALL ON	Anotacoes	REBUILD
ALTER INDEX ALL ON	Tabelas_Preco_Desconto_Importacao	REBUILD
ALTER INDEX ALL ON	Credito_Cli_For	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Serie	REBUILD
ALTER INDEX ALL ON	Funcionarios_Seguranca	REBUILD
ALTER INDEX ALL ON	Configuracoes_Tabelas	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Composicao	REBUILD
ALTER INDEX ALL ON	Filiais_Grupos_Coleta	REBUILD
ALTER INDEX ALL ON	Pesquisa_3	REBUILD
ALTER INDEX ALL ON	Scanntech_Ultimas_Consultas	REBUILD
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_Cidades_Descarga_Documentos_Fiscais	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Assis_Custo	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Composicao_Custos	REBUILD
ALTER INDEX ALL ON	Movimento_Entrega_Volumes	REBUILD
ALTER INDEX ALL ON	Livro_Ponto	REBUILD
ALTER INDEX ALL ON	Documentos_Autorizados_XML	REBUILD
ALTER INDEX ALL ON	Vendedor_Interno_Dispositivos	REBUILD
ALTER INDEX ALL ON	Prod_Serv_FCI	REBUILD
ALTER INDEX ALL ON	Dias_Abertos	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Composicao_Itens	REBUILD
ALTER INDEX ALL ON	PAF_WebServices	REBUILD
ALTER INDEX ALL ON	Funcionarios_Operacoes_Bloqueadas_Saida	REBUILD
ALTER INDEX ALL ON	Atualizacao_Versao	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_MP_Geradas	REBUILD
ALTER INDEX ALL ON	NFe_Destinadas_Notas_Eventos	REBUILD
ALTER INDEX ALL ON	Veiculos_Reboques	REBUILD
ALTER INDEX ALL ON	Envio_Avulso	REBUILD
ALTER INDEX ALL ON	Composicao_Custos	REBUILD
ALTER INDEX ALL ON	Movimento_Ordem_Servico	REBUILD
ALTER INDEX ALL ON	Consignacoes_Lock	REBUILD
ALTER INDEX ALL ON	Fila_Envio_Documentos	REBUILD
ALTER INDEX ALL ON	Adquirentes	REBUILD
ALTER INDEX ALL ON	Contagem_Estoque_Itens	REBUILD
ALTER INDEX ALL ON	Contagem_Estoque_Itens_Series_Excluidas	REBUILD
ALTER INDEX ALL ON	Classe_Imposto_Operacao	REBUILD
ALTER INDEX ALL ON	Agenda_Funcionarios	REBUILD
ALTER INDEX ALL ON	Bridge_Controle_Importacao_Movimentacoes_Sobrepostos	REBUILD
ALTER INDEX ALL ON	NFe_Manifestacoes_Recebidas	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_Importacao_Origem	REBUILD
ALTER INDEX ALL ON	Cli_For_Classes	REBUILD
ALTER INDEX ALL ON	Funcionarios_Tab_Bloqueadas	REBUILD
ALTER INDEX ALL ON	PAF_Credenciamento	REBUILD
ALTER INDEX ALL ON	Bancos	REBUILD
ALTER INDEX ALL ON	Centro_Custo	REBUILD
ALTER INDEX ALL ON	Agenda_Grupos	REBUILD
ALTER INDEX ALL ON	Configuracoes_Fontes_Impressao	REBUILD
ALTER INDEX ALL ON	Dados_Diario_ECF_Detalhes	REBUILD
ALTER INDEX ALL ON	Filiais	REBUILD
ALTER INDEX ALL ON	Funcionarios_Vales	REBUILD
ALTER INDEX ALL ON	Log_V2	REBUILD
ALTER INDEX ALL ON	Movimento	REBUILD
ALTER INDEX ALL ON	Contas_Consumo_Itens	REBUILD
ALTER INDEX ALL ON	Carga_Tributaria	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Agregados	REBUILD
ALTER INDEX ALL ON	Liberacao	REBUILD
ALTER INDEX ALL ON	Composicao_Etapa_Producao	REBUILD
ALTER INDEX ALL ON	Movimento_Centralizacao_Relacionamento_Op_Aut_Itens	REBUILD
ALTER INDEX ALL ON	PAF_Historico_Envio	REBUILD
ALTER INDEX ALL ON	Anotacoes_Funcionarios	REBUILD
ALTER INDEX ALL ON	Movimento_Saida_Entrada_Devolvida	REBUILD
ALTER INDEX ALL ON	Pesquisa_2	REBUILD
ALTER INDEX ALL ON	Cli_For_Fotos	REBUILD
ALTER INDEX ALL ON	Parametros_MFe	REBUILD
ALTER INDEX ALL ON	NFe_Destinadas	REBUILD
ALTER INDEX ALL ON	Parametros_Fiscal_Data_Alteracao	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_Pedido_Venda_Entrega	REBUILD
ALTER INDEX ALL ON	Financeiro_Conta_Caderno_Relacao_Quitacao	REBUILD
ALTER INDEX ALL ON	Meios_Pagamento_ECF	REBUILD
ALTER INDEX ALL ON	Anotacoes_Grupos	REBUILD
ALTER INDEX ALL ON	NFe_Eventos	REBUILD
ALTER INDEX ALL ON	Prod_Serv	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_VEF_Relacionamento	REBUILD
ALTER INDEX ALL ON	Bandeiras_Cartao	REBUILD
ALTER INDEX ALL ON	Contas_Bancarias_Filial_Exclusiva	REBUILD
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_V2	REBUILD
ALTER INDEX ALL ON	Frete_Estado	REBUILD
ALTER INDEX ALL ON	NFe_Contingencia	REBUILD
ALTER INDEX ALL ON	NFe_Inutilizadas	REBUILD
ALTER INDEX ALL ON	Configuracoes_Ordem_Servico_Situacoes	REBUILD
ALTER INDEX ALL ON	Grupos_Filiais_Distribuicao	REBUILD
ALTER INDEX ALL ON	Consignacoes	REBUILD
ALTER INDEX ALL ON	Configuracao_Imprimir_Precos	REBUILD
ALTER INDEX ALL ON	Financeiro_Formas_Recebimento_Pagamento_Contas_TEF_v2	REBUILD
ALTER INDEX ALL ON	Frete_Peso	REBUILD
ALTER INDEX ALL ON	Departamentos	REBUILD
ALTER INDEX ALL ON	Entidade_Beneficiaria	REBUILD
ALTER INDEX ALL ON	Localizacoes	REBUILD
ALTER INDEX ALL ON	Configuracoes_Envio_Email_Mala_Direta	REBUILD
ALTER INDEX ALL ON	Ordens_Producao	REBUILD
ALTER INDEX ALL ON	Financeiro_Caixa	REBUILD
ALTER INDEX ALL ON	Configuracoes_Ordem_Servico_Tipos	REBUILD
ALTER INDEX ALL ON	Layout_Impressao	REBUILD
ALTER INDEX ALL ON	Documento_Funcionarios	REBUILD
ALTER INDEX ALL ON	Veiculos_Reboques_Condutores	REBUILD
ALTER INDEX ALL ON	Filiais_Classes_Estoque_Carol	REBUILD
ALTER INDEX ALL ON	Grupos_Filiais_Distribuicao_Filial	REBUILD
ALTER INDEX ALL ON	Log_MFe	REBUILD
ALTER INDEX ALL ON	Envio_Avulso_Correios	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Desconto_Periodo	REBUILD
ALTER INDEX ALL ON	MFe_Compartilhado_Maquinas	REBUILD
ALTER INDEX ALL ON	Sequencia_Mov	REBUILD
ALTER INDEX ALL ON	NFe_Destinadas_CCe	REBUILD
ALTER INDEX ALL ON	Movimento_Transferencias	REBUILD
ALTER INDEX ALL ON	MFE_Compartilhado_Pedidos	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Localizacoes	REBUILD
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_Conhecimento_Frete	REBUILD
ALTER INDEX ALL ON	Financeiro_Contas_Bancarias_Lancamentos	REBUILD
ALTER INDEX ALL ON	Movimento_Centralizacao_Relacionamento	REBUILD
ALTER INDEX ALL ON	Codigos_Promocionais	REBUILD
ALTER INDEX ALL ON	Cli_For_Mala	REBUILD
ALTER INDEX ALL ON	MFE_Compartilhado_Pedidos_Cancelamento	REBUILD
ALTER INDEX ALL ON	Documento_Grupos	REBUILD
ALTER INDEX ALL ON	Movimento_Centralizacao_Relacionamento_CD	REBUILD
ALTER INDEX ALL ON	Ordens_Producao_Comentarios	REBUILD
ALTER INDEX ALL ON	Chat_Conversas	REBUILD
ALTER INDEX ALL ON	Codigos_Promocionais_Filiais_Permitido	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Fracionamento	REBUILD
ALTER INDEX ALL ON	Carregamentos_Veiculos	REBUILD
ALTER INDEX ALL ON	MFE_Compartilhado_Pedidos_Consulta	REBUILD
ALTER INDEX ALL ON	Filiais_IE_Substituto	REBUILD
ALTER INDEX ALL ON	Favoritos	REBUILD
ALTER INDEX ALL ON	Movimento_Centralizacao_Relacionamento_Entrada	REBUILD
ALTER INDEX ALL ON	Configuracoes_Tabelas_Divisao	REBUILD
ALTER INDEX ALL ON	Cidades	REBUILD
ALTER INDEX ALL ON	Configuracoes_Documentos	REBUILD
ALTER INDEX ALL ON	Operacoes_Limitacoes	REBUILD
ALTER INDEX ALL ON	Financeiro_Formas_Recebimento_Pagamento_PIX_V2	REBUILD
ALTER INDEX ALL ON	Codigos_Promocionais_Filiais_Restrito	REBUILD
ALTER INDEX ALL ON	Movimento_Cotacao_Compra_Precos	REBUILD
ALTER INDEX ALL ON	Movimento_Centralizacao_Relacionamento_Op_Aut	REBUILD
ALTER INDEX ALL ON	Movimento_Centralizacao_Relacionamento_Entrada_Itens	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_Serie	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_Encomendas	REBUILD
ALTER INDEX ALL ON	Configuracoes	REBUILD
ALTER INDEX ALL ON	Fila_Envio_Email	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Comissao_Filial	REBUILD
ALTER INDEX ALL ON	Feriados	REBUILD
ALTER INDEX ALL ON	Paises	REBUILD
ALTER INDEX ALL ON	Codigos_Promocionais_Tabelas_Preco_Permitido	REBUILD
ALTER INDEX ALL ON	A_Fazer	REBUILD
ALTER INDEX ALL ON	Remarcacao_Precos_Regras	REBUILD
ALTER INDEX ALL ON	Documentos	REBUILD
ALTER INDEX ALL ON	Atualizacao	REBUILD
ALTER INDEX ALL ON	Caixas_Fechamento_Lock	REBUILD
ALTER INDEX ALL ON	Configuracoes_Impressoras	REBUILD
ALTER INDEX ALL ON	Carregamentos_Veiculos_MDFe	REBUILD
ALTER INDEX ALL ON	Ordens_Producao_Itens	REBUILD
ALTER INDEX ALL ON	Movimento_Movimento_Documentos_Fiscais_MDFe	REBUILD
ALTER INDEX ALL ON	Sync_Cupons_Cancelados	REBUILD
ALTER INDEX ALL ON	CEST	REBUILD
ALTER INDEX ALL ON	Codigos_Promocionais_Tabelas_Preco_Restrito	REBUILD
ALTER INDEX ALL ON	Log_Conciliacao_Nuvem	REBUILD
ALTER INDEX ALL ON	NFe_Destinadas_Notas	REBUILD
ALTER INDEX ALL ON	Centro_Custo_Departamento	REBUILD
ALTER INDEX ALL ON	Configuracoes_Ordem_Servico_Atrasos	REBUILD
ALTER INDEX ALL ON	Contatos_Efetuados_Tipos	REBUILD
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_Cidades_Carregamento	REBUILD
ALTER INDEX ALL ON	NFe_WebServices	REBUILD
ALTER INDEX ALL ON	Log_MFE_V2	REBUILD
ALTER INDEX ALL ON	Mensagens_Nota	REBUILD
ALTER INDEX ALL ON	Cli_For_Codigos_Promocionais	REBUILD
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_VEF	REBUILD
ALTER INDEX ALL ON	Dados_Diario_ECF	REBUILD
ALTER INDEX ALL ON	Contagem_Estoque_Movimentos_Gerados	REBUILD
ALTER INDEX ALL ON	Financeiro_Int_CTC_CBL	REBUILD
ALTER INDEX ALL ON	Tabelas_Preco	REBUILD
ALTER INDEX ALL ON	Distribuicao_Estoque	REBUILD
ALTER INDEX ALL ON	Classe_Imposto	REBUILD
ALTER INDEX ALL ON	Financeiro_Baixa_Cnab_Grupo	REBUILD
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_Cidades_Descarga	REBUILD
ALTER INDEX ALL ON	Otica_Disponibilidades_Lentes	REBUILD
ALTER INDEX ALL ON	Passos_Cobranca	REBUILD
ALTER INDEX ALL ON	Movimento_Entrega_Parcial_Relacionamento	REBUILD
ALTER INDEX ALL ON	Cores	REBUILD
ALTER INDEX ALL ON	Movimento_Codigos_Promocionais	REBUILD
ALTER INDEX ALL ON	Log_Geral	REBUILD
ALTER INDEX ALL ON	Grupo_Operacoes	REBUILD
ALTER INDEX ALL ON	Whatsapp_Celulares_Habilitados	REBUILD
ALTER INDEX ALL ON	Filiais_CFOP_Composicao_Materia_Prima	REBUILD
ALTER INDEX ALL ON	MobileSync_Visitas	REBUILD
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_Condutores	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_Exportacao	REBUILD
ALTER INDEX ALL ON	Movimento_Ordem_Servico_Importada	REBUILD
ALTER INDEX ALL ON	Pesquisa_1	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Precos_Faixa_Qtde	REBUILD
ALTER INDEX ALL ON	POS	REBUILD
ALTER INDEX ALL ON	Dados_Diarios_Abre_Dia	REBUILD
ALTER INDEX ALL ON	Contas_Bancarias	REBUILD
ALTER INDEX ALL ON	Grid_Consignacoes	REBUILD
ALTER INDEX ALL ON	A_Fazer_Areas	REBUILD
ALTER INDEX ALL ON	MDFe_WebServices	REBUILD
ALTER INDEX ALL ON	Operacao_Grupo_Operacoes	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Fotos	REBUILD
ALTER INDEX ALL ON	Exporta_Web_Recibos_Mov	REBUILD
ALTER INDEX ALL ON	Prod_Serv_NVE	REBUILD
ALTER INDEX ALL ON	Whatsapp_Registro_Mensagens	REBUILD
ALTER INDEX ALL ON	Classes	REBUILD
ALTER INDEX ALL ON	Financeiro_Contas_Historico	REBUILD
ALTER INDEX ALL ON	Ordens_Producao_Itens_Materia_Prima	REBUILD
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_Vale_Pedagio	REBUILD
ALTER INDEX ALL ON	Bridge_Filial	REBUILD
ALTER INDEX ALL ON	MobileSync_Registros_Recebidos	REBUILD
ALTER INDEX ALL ON	Parametros_Fiscal	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_Detalhe_Documentos_Fiscais	REBUILD
ALTER INDEX ALL ON	Fidelidade_Cli_For_Extrato	REBUILD
ALTER INDEX ALL ON	Configuracoes_Central_Controle	REBUILD
ALTER INDEX ALL ON	Unidades_Venda	REBUILD
ALTER INDEX ALL ON	Layout_Impressao_Linhas_Variaveis	REBUILD
ALTER INDEX ALL ON	Financeiro_Formas_Recebimento_Pagamento_Cheques_Clientes_V2	REBUILD
ALTER INDEX ALL ON	Meta_Funcionario	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Promocao	REBUILD
ALTER INDEX ALL ON	Movimento_Link_Pagamento	REBUILD
ALTER INDEX ALL ON	Operacoes	REBUILD
ALTER INDEX ALL ON	Financeiro_Formas_Recebimento_Pagamento_Lancamentos_Bancarios_V2	REBUILD
ALTER INDEX ALL ON	NFe_WebServices4	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_Consignacao	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv	REBUILD
ALTER INDEX ALL ON	Movimento_Cotacao_Compra	REBUILD
ALTER INDEX ALL ON	Moedas	REBUILD
ALTER INDEX ALL ON	Configuracoes_Central_Controle_Informacoes	REBUILD
ALTER INDEX ALL ON	Fidelidade_Pontos_Cli_For	REBUILD
ALTER INDEX ALL ON	Protestos	REBUILD
ALTER INDEX ALL ON	MDFe_Nao_Encerrados	REBUILD
ALTER INDEX ALL ON	Layout_Impressao_Campos	REBUILD
ALTER INDEX ALL ON	MobileSync_Operacoes	REBUILD
ALTER INDEX ALL ON	SAT_Compartilhado_Maquinas	REBUILD
ALTER INDEX ALL ON	Movimento_Entrega_Volumes_Lacres	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_DI_Adicao	REBUILD
ALTER INDEX ALL ON	Geral	REBUILD
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_Referenciados_V103	REBUILD
ALTER INDEX ALL ON	Funcionarios_Situacoes_OS	REBUILD
ALTER INDEX ALL ON	Encomendas	REBUILD
ALTER INDEX ALL ON	SAT_Compartilhado_Pedidos	REBUILD
ALTER INDEX ALL ON	Log_V2_Maquinas	REBUILD
ALTER INDEX ALL ON	Analise_Compras	REBUILD
ALTER INDEX ALL ON	Configuracoes_Central_Controle_Informacoes_Condicoes	REBUILD
ALTER INDEX ALL ON	Grupo_Cli_For	REBUILD
ALTER INDEX ALL ON	Financeiro_Formas_Recebimento_Pagamento_V2	REBUILD
ALTER INDEX ALL ON	SAT_Compartilhado_Pedidos_Cancelamento	REBUILD
ALTER INDEX ALL ON	Grupos	REBUILD
ALTER INDEX ALL ON	Tamanhos	REBUILD
ALTER INDEX ALL ON	Ordens_Producao_Relacao_Movimento	REBUILD
ALTER INDEX ALL ON	Operacoes_Filiais	REBUILD
ALTER INDEX ALL ON	MDFe_Eventos	REBUILD
ALTER INDEX ALL ON	Analise_Compras_Movimentos_Gerados	REBUILD
ALTER INDEX ALL ON	Movimento_Transferencias_Importacoes	REBUILD
ALTER INDEX ALL ON	Estoque_Atual_Cli_For_Data_Alteracao	REBUILD
ALTER INDEX ALL ON	Documentos_Areas	REBUILD
ALTER INDEX ALL ON	Mensagem_Cidade_Estado	REBUILD
ALTER INDEX ALL ON	Promocoes_Especiais	REBUILD
ALTER INDEX ALL ON	Movimento_Cotacao_Compra_Fornecedores	REBUILD
ALTER INDEX ALL ON	Cli_For_Grupo_Cli_For	REBUILD
ALTER INDEX ALL ON	Enquadramento_IPI	REBUILD
ALTER INDEX ALL ON	NFCe_Contingencia_Automatica	REBUILD
ALTER INDEX ALL ON	Administradoras_Cartao_Filial_Conta	REBUILD
ALTER INDEX ALL ON	Codigo_ANP	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Edicao	REBUILD
ALTER INDEX ALL ON	Contagem_Estoque	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_DI	REBUILD
ALTER INDEX ALL ON	Movimento_VEF_Lock	REBUILD
ALTER INDEX ALL ON	NFCe_Contingencia_Automatica_Mensagem_Operador	REBUILD
ALTER INDEX ALL ON	Contas_Bancarias_Funcionarios	REBUILD
ALTER INDEX ALL ON	Financeiro_Sangria_Historico	REBUILD
ALTER INDEX ALL ON	Licencas	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_Devolucao_Simplificada	REBUILD
ALTER INDEX ALL ON	Movimento_Cotacao_Compra_Prod_Serv	REBUILD
ALTER INDEX ALL ON	Bridge_Calendario	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Similares	REBUILD
ALTER INDEX ALL ON	Transporte_Transportadora	REBUILD
ALTER INDEX ALL ON	Configuracoes_Divisao_Cli_For_Plano_Pagamento	REBUILD
ALTER INDEX ALL ON	Parametros_SAT	REBUILD
ALTER INDEX ALL ON	Carga_Tributaria_Estados	REBUILD
ALTER INDEX ALL ON	Administradoras_Cartao	REBUILD
ALTER INDEX ALL ON	Movimento_Entrega_Motivo	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Lote	REBUILD
ALTER INDEX ALL ON	Avisos_Temporarios_Funcionarios	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_Quantidade_Entregue	REBUILD
ALTER INDEX ALL ON	Integrador_Evencard_Vendas_Exportadas	REBUILD
ALTER INDEX ALL ON	Movimento_Reserva	REBUILD
ALTER INDEX ALL ON	Motivo_Desefetivacao	REBUILD
ALTER INDEX ALL ON	Emails_Enviados	REBUILD
ALTER INDEX ALL ON	Cotacoes	REBUILD
ALTER INDEX ALL ON	Ultimos_Acessos	REBUILD
ALTER INDEX ALL ON	Grupos_Funcionarios	REBUILD
ALTER INDEX ALL ON	Fila_MFe	REBUILD
ALTER INDEX ALL ON	Bridge_Controle_Importacao_Movimentacoes	REBUILD
ALTER INDEX ALL ON	Movimento_Entrada_Transferencia_Automatica	REBUILD
ALTER INDEX ALL ON	Tabelas_Preco_Cli_For_Classes	REBUILD
ALTER INDEX ALL ON	Promocoes_Especiais_Filiais	REBUILD
ALTER INDEX ALL ON	Financeiro_Icms_Partilha_Relacao	REBUILD
ALTER INDEX ALL ON	Promocoes_Especiais_Prod_Serv	REBUILD
ALTER INDEX ALL ON	Controle_Versoes	REBUILD
ALTER INDEX ALL ON	Meios_Pagamento_PAF_NFCe	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Grade	REBUILD
ALTER INDEX ALL ON	Campos_Imprimir_Preco	REBUILD
ALTER INDEX ALL ON	Log_SAT	REBUILD
ALTER INDEX ALL ON	Movimento_Checkout	REBUILD
ALTER INDEX ALL ON	Recentes	REBUILD
ALTER INDEX ALL ON	Luxottica_Sequencia	REBUILD
ALTER INDEX ALL ON	Funcionarios	REBUILD
ALTER INDEX ALL ON	Registro_Maquinas	REBUILD
ALTER INDEX ALL ON	NBS	REBUILD
ALTER INDEX ALL ON	Contas_Bancarias_Lock	REBUILD
ALTER INDEX ALL ON	AutoSync_Modulos	REBUILD
ALTER INDEX ALL ON	Log_Fila_MFe	REBUILD
ALTER INDEX ALL ON	Configuracoes_Customizavel	REBUILD
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_Inutilizados	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Carga_Tributaria	REBUILD
ALTER INDEX ALL ON	Z_IdealSoft	REBUILD
ALTER INDEX ALL ON	Registro_Acoes	REBUILD
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_UF_Percurso	REBUILD
ALTER INDEX ALL ON	NCM_Sistema	REBUILD
ALTER INDEX ALL ON	Subclasses	REBUILD
ALTER INDEX ALL ON	Financeiro_Formas_Recebimento_Pagamento_Contas_V2	REBUILD
ALTER INDEX ALL ON	Luxottica_Codigos_Filiais	REBUILD
ALTER INDEX ALL ON	Chat_Mensagens	REBUILD
ALTER INDEX ALL ON	Plano_Contas2	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_Promocoes_Especiais	REBUILD
ALTER INDEX ALL ON	Mensagens	REBUILD
ALTER INDEX ALL ON	Familias	REBUILD
ALTER INDEX ALL ON	Mensagens_Funcionarios	REBUILD
ALTER INDEX ALL ON	Agenda	REBUILD
ALTER INDEX ALL ON	Caixas_Movimentacao_Lock	REBUILD
ALTER INDEX ALL ON	Contagem_Estoque_Itens_Lotes	REBUILD
ALTER INDEX ALL ON	NFe_Prorrogacao	REBUILD
ALTER INDEX ALL ON	Contas_Contabeis	REBUILD
ALTER INDEX ALL ON	Caixas_Funcionarios_Relatorio	REBUILD
ALTER INDEX ALL ON	Cli_For_Documentos_Autorizados_XML	REBUILD
ALTER INDEX ALL ON	Bridge_Calendario_Detalhe	REBUILD
ALTER INDEX ALL ON	Grupos_Mala	REBUILD
ALTER INDEX ALL ON	Luxottica_Movimento_Exportado	REBUILD
ALTER INDEX ALL ON	Boletos_Liberacao	REBUILD
ALTER INDEX ALL ON	Contas_Contabeis_Filiais	REBUILD
ALTER INDEX ALL ON	Noticias_Personalizadas	REBUILD
ALTER INDEX ALL ON	Configuracoes_Email_Layout	REBUILD
ALTER INDEX ALL ON	Identificadores_Pagamento_MFe	REBUILD
ALTER INDEX ALL ON	Configuracoes_Customizavel_Registro	REBUILD
ALTER INDEX ALL ON	Movimento_DAV	REBUILD
ALTER INDEX ALL ON	Funcionarios_Fotos	REBUILD
ALTER INDEX ALL ON	Mala_Direta	REBUILD
ALTER INDEX ALL ON	NCM	REBUILD
ALTER INDEX ALL ON	Contagem_Estoque_Itens_Series	REBUILD
ALTER INDEX ALL ON	Usuarios_Ativos	REBUILD
ALTER INDEX ALL ON	Noticias_Personalizadas_Filiais	REBUILD
ALTER INDEX ALL ON	Layout_Impressao_Linhas_Etiqueta	REBUILD
ALTER INDEX ALL ON	Motivo_Desconto	REBUILD
ALTER INDEX ALL ON	MobileSync_Funcionarios_Regiao	REBUILD
ALTER INDEX ALL ON	Plano_Contas3	REBUILD
ALTER INDEX ALL ON	Movimento_Origem	REBUILD
ALTER INDEX ALL ON	Funcionarios_Filiais_Permitido	REBUILD
ALTER INDEX ALL ON	Noticias_Personalizadas_Funcionarios_Lidos	REBUILD
ALTER INDEX ALL ON	Configuracoes_Maquina	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_Troca	REBUILD
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_Lacres	REBUILD
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais	REBUILD
ALTER INDEX ALL ON	Grupos_Filiais_MobileView	REBUILD
ALTER INDEX ALL ON	Compromissos_Grupos	REBUILD
ALTER INDEX ALL ON	Cli_For_Limite_Credito	REBUILD
ALTER INDEX ALL ON	Frete	REBUILD
ALTER INDEX ALL ON	Estoque_Atual_Lote	REBUILD
ALTER INDEX ALL ON	Entrega_Transportes	REBUILD
ALTER INDEX ALL ON	Funcionarios_Filiais_Restrito	REBUILD
ALTER INDEX ALL ON	Funcionarios_Senha_Avancada	REBUILD
ALTER INDEX ALL ON	Caixas_Funcionarios_Fazer_Venda	REBUILD
ALTER INDEX ALL ON	Campanhas	REBUILD
ALTER INDEX ALL ON	Recibos_Descricao	REBUILD
ALTER INDEX ALL ON	Configuracoes_Customizavel_Titulo	REBUILD
ALTER INDEX ALL ON	Otica_Laboratorios	REBUILD
ALTER INDEX ALL ON	Classificacao_Abc	REBUILD
ALTER INDEX ALL ON	Funcionarios_Conf	REBUILD
ALTER INDEX ALL ON	Cli_For_Contatos_Efetuados	REBUILD
ALTER INDEX ALL ON	Fabricantes	REBUILD
ALTER INDEX ALL ON	sysdiagrams	REBUILD
ALTER INDEX ALL ON	Configuracoes_Filtros	REBUILD
ALTER INDEX ALL ON	Movimento_Dados_NFSe	REBUILD
ALTER INDEX ALL ON	NFe_Prorrogacao_Eventos	REBUILD
ALTER INDEX ALL ON	Filiais_MobileView	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_Troca_Utilizadas	REBUILD
ALTER INDEX ALL ON	Meta_Venda	REBUILD
ALTER INDEX ALL ON	Otica_Status	REBUILD
ALTER INDEX ALL ON	Scanntech_Fechamento_Diario_Exportado	REBUILD
ALTER INDEX ALL ON	Grupos_Passos_Cobranca	REBUILD
ALTER INDEX ALL ON	Movimento_Saida_Transferencia_Automatica	REBUILD
ALTER INDEX ALL ON	Financeiro_Caixa_Grupo	REBUILD
ALTER INDEX ALL ON	Estoque_Atual_Cli_For	REBUILD
ALTER INDEX ALL ON	Funcionarios_Grupos	REBUILD
ALTER INDEX ALL ON	Financeiro_Contas_MobileView	REBUILD
ALTER INDEX ALL ON	Financeiro_Contas	REBUILD
ALTER INDEX ALL ON	Caixas_Funcionarios_Desfazer_Venda	REBUILD
ALTER INDEX ALL ON	Plano_Contas1	REBUILD
ALTER INDEX ALL ON	NVE	REBUILD
ALTER INDEX ALL ON	Sync_Contra_Senha_Geradas	REBUILD
ALTER INDEX ALL ON	Remarcacao_Precos	REBUILD
ALTER INDEX ALL ON	Estoque_Atual_Serie	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Nat_Rec	REBUILD
ALTER INDEX ALL ON	Funcionarios_MobileView	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_Troca_Origem	REBUILD
ALTER INDEX ALL ON	Funcionarios_Operacoes_Entrada	REBUILD
ALTER INDEX ALL ON	Imagens_Telas	REBUILD
ALTER INDEX ALL ON	Cli_For_Mobile_Sync	REBUILD
ALTER INDEX ALL ON	Transporte_Proprio	REBUILD
ALTER INDEX ALL ON	Agenda_Areas	REBUILD
ALTER INDEX ALL ON	MobileView_Filiais	REBUILD
ALTER INDEX ALL ON	Cli_For	REBUILD
ALTER INDEX ALL ON	Movimento_Financeiro	REBUILD
ALTER INDEX ALL ON	Caixas	REBUILD
ALTER INDEX ALL ON	Funcionarios_Caixas_Padrao	REBUILD
ALTER INDEX ALL ON	Contas_Consumo	REBUILD
ALTER INDEX ALL ON	Noticias_Personalizadas_MobileView	REBUILD
ALTER INDEX ALL ON	Classes_MobileView	REBUILD
ALTER INDEX ALL ON	Caixas_Funcionarios_Movimento	REBUILD
ALTER INDEX ALL ON	Funcionarios_Operacoes_Saida	REBUILD
ALTER INDEX ALL ON	Financeiro_Cobranca_Passos	REBUILD
ALTER INDEX ALL ON	Vendedor_Interno_Usuarios_Logados	REBUILD
ALTER INDEX ALL ON	Movimento_MobileView	REBUILD
ALTER INDEX ALL ON	Ordens_Producao_Insumos_Consumidos	REBUILD
ALTER INDEX ALL ON	Grupo_Remarcacao_Precos	REBUILD
ALTER INDEX ALL ON	NFe_Prorrogacao_Itens	REBUILD
ALTER INDEX ALL ON	Grupos_Filiais	REBUILD
ALTER INDEX ALL ON	Subclasses_MobileView	REBUILD
ALTER INDEX ALL ON	Transporte_Proprio_Condutores	REBUILD
ALTER INDEX ALL ON	Segurancas	REBUILD
ALTER INDEX ALL ON	Movimento_Prod_Serv_MobileView	REBUILD
ALTER INDEX ALL ON	Ordens_Producao_Itens_Produzidos	REBUILD
ALTER INDEX ALL ON	Estoque_Atual	REBUILD
ALTER INDEX ALL ON	Scanntech_Fechamento_Promocao_Exportado	REBUILD
ALTER INDEX ALL ON	Info_Sync	REBUILD
ALTER INDEX ALL ON	Campanhas_Itens	REBUILD
ALTER INDEX ALL ON	Credito_Cli_For_Movimento_Atrelado	REBUILD
ALTER INDEX ALL ON	Grupos_MobileView	REBUILD
ALTER INDEX ALL ON	Movimento_Mobile_Sync	REBUILD
ALTER INDEX ALL ON	Movimento_Entrega	REBUILD
ALTER INDEX ALL ON	Filiais_Certificados	REBUILD
ALTER INDEX ALL ON	Motivo_Devolucao	REBUILD
ALTER INDEX ALL ON	Recibos	REBUILD
ALTER INDEX ALL ON	Compromissos	REBUILD
ALTER INDEX ALL ON	CFOP	REBUILD
ALTER INDEX ALL ON	Agenda_Contatos	REBUILD
ALTER INDEX ALL ON	Antecipacao_Financeira_Historico	REBUILD
ALTER INDEX ALL ON	Familias_MobileView	REBUILD
ALTER INDEX ALL ON	Configuracoes_Email	REBUILD
ALTER INDEX ALL ON	Parametros_Scanntech	REBUILD
ALTER INDEX ALL ON	Filiais_CFOP_Ignorar_Custo	REBUILD
ALTER INDEX ALL ON	Funcionarios_Historico	REBUILD
ALTER INDEX ALL ON	Caixas_Funcionarios_Transferencia	REBUILD
ALTER INDEX ALL ON	Grupo_Remarcacao_Precos_Regras	REBUILD
ALTER INDEX ALL ON	Filiais_Grupos_Filiais	REBUILD
ALTER INDEX ALL ON	Prod_Serv_Precos	REBUILD
ALTER INDEX ALL ON	Estoque_Atual_MobileView	REBUILD
		
ALTER INDEX ALL ON	Cli_For_Contatos	REORGANIZE
ALTER INDEX ALL ON	Campanhas_MobileView	REORGANIZE
ALTER INDEX ALL ON	Demais_Documentos_ECF	REORGANIZE
ALTER INDEX ALL ON	Compromissos_Agrupamento	REORGANIZE
ALTER INDEX ALL ON	Compromissos_Funcionarios	REORGANIZE
ALTER INDEX ALL ON	Parametros_Scanntech_Filiais	REORGANIZE
ALTER INDEX ALL ON	Resultados_Campanhas_MobileView	REORGANIZE
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_Referenciados	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Gerador_Relatorios	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Cobranca_Passos_Historico	REORGANIZE
ALTER INDEX ALL ON	Movimento_Ordem_Producao	REORGANIZE
ALTER INDEX ALL ON	Recebimento_Nao_Fiscal_ECF	REORGANIZE
ALTER INDEX ALL ON	A_Fazer_Funcionarios	REORGANIZE
ALTER INDEX ALL ON	Sequencia_Operacao	REORGANIZE
ALTER INDEX ALL ON	Etiquetas_Pendentes	REORGANIZE
ALTER INDEX ALL ON	Grupos_Coleta	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Pastas_Mensagens	REORGANIZE
ALTER INDEX ALL ON	Movimento_PV	REORGANIZE
ALTER INDEX ALL ON	Parametros_Scanntech_Urls	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Operacoes_Bloqueadas_Entrada	REORGANIZE
ALTER INDEX ALL ON	Retorno_SAT	REORGANIZE
ALTER INDEX ALL ON	Compromissos_Agrupamento_Funcionarios	REORGANIZE
ALTER INDEX ALL ON	Movimento_Ordem_Producao_Comentarios	REORGANIZE
ALTER INDEX ALL ON	A_Fazer_Grupos	REORGANIZE
ALTER INDEX ALL ON	Motivo_Cancelamento_Orcamento	REORGANIZE
ALTER INDEX ALL ON	Scanntech_Movimento_Exportado	REORGANIZE
ALTER INDEX ALL ON	SAT_Compartilhado_Pedidos_Consulta	REORGANIZE
ALTER INDEX ALL ON	Cli_For_Credito_Lock	REORGANIZE
ALTER INDEX ALL ON	Noticia	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_Ordem_Producao	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_Lote	REORGANIZE
ALTER INDEX ALL ON	Anotacoes	REORGANIZE
ALTER INDEX ALL ON	Tabelas_Preco_Desconto_Importacao	REORGANIZE
ALTER INDEX ALL ON	Credito_Cli_For	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Serie	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Seguranca	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Tabelas	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Composicao	REORGANIZE
ALTER INDEX ALL ON	Filiais_Grupos_Coleta	REORGANIZE
ALTER INDEX ALL ON	Pesquisa_3	REORGANIZE
ALTER INDEX ALL ON	Scanntech_Ultimas_Consultas	REORGANIZE
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_Cidades_Descarga_Documentos_Fiscais	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Assis_Custo	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Composicao_Custos	REORGANIZE
ALTER INDEX ALL ON	Movimento_Entrega_Volumes	REORGANIZE
ALTER INDEX ALL ON	Livro_Ponto	REORGANIZE
ALTER INDEX ALL ON	Documentos_Autorizados_XML	REORGANIZE
ALTER INDEX ALL ON	Vendedor_Interno_Dispositivos	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_FCI	REORGANIZE
ALTER INDEX ALL ON	Dias_Abertos	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Composicao_Itens	REORGANIZE
ALTER INDEX ALL ON	PAF_WebServices	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Operacoes_Bloqueadas_Saida	REORGANIZE
ALTER INDEX ALL ON	Atualizacao_Versao	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_MP_Geradas	REORGANIZE
ALTER INDEX ALL ON	NFe_Destinadas_Notas_Eventos	REORGANIZE
ALTER INDEX ALL ON	Veiculos_Reboques	REORGANIZE
ALTER INDEX ALL ON	Envio_Avulso	REORGANIZE
ALTER INDEX ALL ON	Composicao_Custos	REORGANIZE
ALTER INDEX ALL ON	Movimento_Ordem_Servico	REORGANIZE
ALTER INDEX ALL ON	Consignacoes_Lock	REORGANIZE
ALTER INDEX ALL ON	Fila_Envio_Documentos	REORGANIZE
ALTER INDEX ALL ON	Adquirentes	REORGANIZE
ALTER INDEX ALL ON	Contagem_Estoque_Itens	REORGANIZE
ALTER INDEX ALL ON	Contagem_Estoque_Itens_Series_Excluidas	REORGANIZE
ALTER INDEX ALL ON	Classe_Imposto_Operacao	REORGANIZE
ALTER INDEX ALL ON	Agenda_Funcionarios	REORGANIZE
ALTER INDEX ALL ON	Bridge_Controle_Importacao_Movimentacoes_Sobrepostos	REORGANIZE
ALTER INDEX ALL ON	NFe_Manifestacoes_Recebidas	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_Importacao_Origem	REORGANIZE
ALTER INDEX ALL ON	Cli_For_Classes	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Tab_Bloqueadas	REORGANIZE
ALTER INDEX ALL ON	PAF_Credenciamento	REORGANIZE
ALTER INDEX ALL ON	Bancos	REORGANIZE
ALTER INDEX ALL ON	Centro_Custo	REORGANIZE
ALTER INDEX ALL ON	Agenda_Grupos	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Fontes_Impressao	REORGANIZE
ALTER INDEX ALL ON	Dados_Diario_ECF_Detalhes	REORGANIZE
ALTER INDEX ALL ON	Filiais	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Vales	REORGANIZE
ALTER INDEX ALL ON	Log_V2	REORGANIZE
ALTER INDEX ALL ON	Movimento	REORGANIZE
ALTER INDEX ALL ON	Contas_Consumo_Itens	REORGANIZE
ALTER INDEX ALL ON	Carga_Tributaria	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Agregados	REORGANIZE
ALTER INDEX ALL ON	Liberacao	REORGANIZE
ALTER INDEX ALL ON	Composicao_Etapa_Producao	REORGANIZE
ALTER INDEX ALL ON	Movimento_Centralizacao_Relacionamento_Op_Aut_Itens	REORGANIZE
ALTER INDEX ALL ON	PAF_Historico_Envio	REORGANIZE
ALTER INDEX ALL ON	Anotacoes_Funcionarios	REORGANIZE
ALTER INDEX ALL ON	Movimento_Saida_Entrada_Devolvida	REORGANIZE
ALTER INDEX ALL ON	Pesquisa_2	REORGANIZE
ALTER INDEX ALL ON	Cli_For_Fotos	REORGANIZE
ALTER INDEX ALL ON	Parametros_MFe	REORGANIZE
ALTER INDEX ALL ON	NFe_Destinadas	REORGANIZE
ALTER INDEX ALL ON	Parametros_Fiscal_Data_Alteracao	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_Pedido_Venda_Entrega	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Conta_Caderno_Relacao_Quitacao	REORGANIZE
ALTER INDEX ALL ON	Meios_Pagamento_ECF	REORGANIZE
ALTER INDEX ALL ON	Anotacoes_Grupos	REORGANIZE
ALTER INDEX ALL ON	NFe_Eventos	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_VEF_Relacionamento	REORGANIZE
ALTER INDEX ALL ON	Bandeiras_Cartao	REORGANIZE
ALTER INDEX ALL ON	Contas_Bancarias_Filial_Exclusiva	REORGANIZE
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_V2	REORGANIZE
ALTER INDEX ALL ON	Frete_Estado	REORGANIZE
ALTER INDEX ALL ON	NFe_Contingencia	REORGANIZE
ALTER INDEX ALL ON	NFe_Inutilizadas	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Ordem_Servico_Situacoes	REORGANIZE
ALTER INDEX ALL ON	Grupos_Filiais_Distribuicao	REORGANIZE
ALTER INDEX ALL ON	Consignacoes	REORGANIZE
ALTER INDEX ALL ON	Configuracao_Imprimir_Precos	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Formas_Recebimento_Pagamento_Contas_TEF_v2	REORGANIZE
ALTER INDEX ALL ON	Frete_Peso	REORGANIZE
ALTER INDEX ALL ON	Departamentos	REORGANIZE
ALTER INDEX ALL ON	Entidade_Beneficiaria	REORGANIZE
ALTER INDEX ALL ON	Localizacoes	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Envio_Email_Mala_Direta	REORGANIZE
ALTER INDEX ALL ON	Ordens_Producao	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Caixa	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Ordem_Servico_Tipos	REORGANIZE
ALTER INDEX ALL ON	Layout_Impressao	REORGANIZE
ALTER INDEX ALL ON	Documento_Funcionarios	REORGANIZE
ALTER INDEX ALL ON	Veiculos_Reboques_Condutores	REORGANIZE
ALTER INDEX ALL ON	Filiais_Classes_Estoque_Carol	REORGANIZE
ALTER INDEX ALL ON	Grupos_Filiais_Distribuicao_Filial	REORGANIZE
ALTER INDEX ALL ON	Log_MFe	REORGANIZE
ALTER INDEX ALL ON	Envio_Avulso_Correios	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Desconto_Periodo	REORGANIZE
ALTER INDEX ALL ON	MFe_Compartilhado_Maquinas	REORGANIZE
ALTER INDEX ALL ON	Sequencia_Mov	REORGANIZE
ALTER INDEX ALL ON	NFe_Destinadas_CCe	REORGANIZE
ALTER INDEX ALL ON	Movimento_Transferencias	REORGANIZE
ALTER INDEX ALL ON	MFE_Compartilhado_Pedidos	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Localizacoes	REORGANIZE
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_Conhecimento_Frete	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Contas_Bancarias_Lancamentos	REORGANIZE
ALTER INDEX ALL ON	Movimento_Centralizacao_Relacionamento	REORGANIZE
ALTER INDEX ALL ON	Codigos_Promocionais	REORGANIZE
ALTER INDEX ALL ON	Cli_For_Mala	REORGANIZE
ALTER INDEX ALL ON	MFE_Compartilhado_Pedidos_Cancelamento	REORGANIZE
ALTER INDEX ALL ON	Documento_Grupos	REORGANIZE
ALTER INDEX ALL ON	Movimento_Centralizacao_Relacionamento_CD	REORGANIZE
ALTER INDEX ALL ON	Ordens_Producao_Comentarios	REORGANIZE
ALTER INDEX ALL ON	Chat_Conversas	REORGANIZE
ALTER INDEX ALL ON	Codigos_Promocionais_Filiais_Permitido	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Fracionamento	REORGANIZE
ALTER INDEX ALL ON	Carregamentos_Veiculos	REORGANIZE
ALTER INDEX ALL ON	MFE_Compartilhado_Pedidos_Consulta	REORGANIZE
ALTER INDEX ALL ON	Filiais_IE_Substituto	REORGANIZE
ALTER INDEX ALL ON	Favoritos	REORGANIZE
ALTER INDEX ALL ON	Movimento_Centralizacao_Relacionamento_Entrada	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Tabelas_Divisao	REORGANIZE
ALTER INDEX ALL ON	Cidades	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Documentos	REORGANIZE
ALTER INDEX ALL ON	Operacoes_Limitacoes	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Formas_Recebimento_Pagamento_PIX_V2	REORGANIZE
ALTER INDEX ALL ON	Codigos_Promocionais_Filiais_Restrito	REORGANIZE
ALTER INDEX ALL ON	Movimento_Cotacao_Compra_Precos	REORGANIZE
ALTER INDEX ALL ON	Movimento_Centralizacao_Relacionamento_Op_Aut	REORGANIZE
ALTER INDEX ALL ON	Movimento_Centralizacao_Relacionamento_Entrada_Itens	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_Serie	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_Encomendas	REORGANIZE
ALTER INDEX ALL ON	Configuracoes	REORGANIZE
ALTER INDEX ALL ON	Fila_Envio_Email	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Comissao_Filial	REORGANIZE
ALTER INDEX ALL ON	Feriados	REORGANIZE
ALTER INDEX ALL ON	Paises	REORGANIZE
ALTER INDEX ALL ON	Codigos_Promocionais_Tabelas_Preco_Permitido	REORGANIZE
ALTER INDEX ALL ON	A_Fazer	REORGANIZE
ALTER INDEX ALL ON	Remarcacao_Precos_Regras	REORGANIZE
ALTER INDEX ALL ON	Documentos	REORGANIZE
ALTER INDEX ALL ON	Atualizacao	REORGANIZE
ALTER INDEX ALL ON	Caixas_Fechamento_Lock	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Impressoras	REORGANIZE
ALTER INDEX ALL ON	Carregamentos_Veiculos_MDFe	REORGANIZE
ALTER INDEX ALL ON	Ordens_Producao_Itens	REORGANIZE
ALTER INDEX ALL ON	Movimento_Movimento_Documentos_Fiscais_MDFe	REORGANIZE
ALTER INDEX ALL ON	Sync_Cupons_Cancelados	REORGANIZE
ALTER INDEX ALL ON	CEST	REORGANIZE
ALTER INDEX ALL ON	Codigos_Promocionais_Tabelas_Preco_Restrito	REORGANIZE
ALTER INDEX ALL ON	Log_Conciliacao_Nuvem	REORGANIZE
ALTER INDEX ALL ON	NFe_Destinadas_Notas	REORGANIZE
ALTER INDEX ALL ON	Centro_Custo_Departamento	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Ordem_Servico_Atrasos	REORGANIZE
ALTER INDEX ALL ON	Contatos_Efetuados_Tipos	REORGANIZE
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_Cidades_Carregamento	REORGANIZE
ALTER INDEX ALL ON	NFe_WebServices	REORGANIZE
ALTER INDEX ALL ON	Log_MFE_V2	REORGANIZE
ALTER INDEX ALL ON	Mensagens_Nota	REORGANIZE
ALTER INDEX ALL ON	Cli_For_Codigos_Promocionais	REORGANIZE
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_VEF	REORGANIZE
ALTER INDEX ALL ON	Dados_Diario_ECF	REORGANIZE
ALTER INDEX ALL ON	Contagem_Estoque_Movimentos_Gerados	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Int_CTC_CBL	REORGANIZE
ALTER INDEX ALL ON	Tabelas_Preco	REORGANIZE
ALTER INDEX ALL ON	Distribuicao_Estoque	REORGANIZE
ALTER INDEX ALL ON	Classe_Imposto	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Baixa_Cnab_Grupo	REORGANIZE
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_Cidades_Descarga	REORGANIZE
ALTER INDEX ALL ON	Otica_Disponibilidades_Lentes	REORGANIZE
ALTER INDEX ALL ON	Passos_Cobranca	REORGANIZE
ALTER INDEX ALL ON	Movimento_Entrega_Parcial_Relacionamento	REORGANIZE
ALTER INDEX ALL ON	Cores	REORGANIZE
ALTER INDEX ALL ON	Movimento_Codigos_Promocionais	REORGANIZE
ALTER INDEX ALL ON	Log_Geral	REORGANIZE
ALTER INDEX ALL ON	Grupo_Operacoes	REORGANIZE
ALTER INDEX ALL ON	Whatsapp_Celulares_Habilitados	REORGANIZE
ALTER INDEX ALL ON	Filiais_CFOP_Composicao_Materia_Prima	REORGANIZE
ALTER INDEX ALL ON	MobileSync_Visitas	REORGANIZE
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_Condutores	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_Exportacao	REORGANIZE
ALTER INDEX ALL ON	Movimento_Ordem_Servico_Importada	REORGANIZE
ALTER INDEX ALL ON	Pesquisa_1	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Precos_Faixa_Qtde	REORGANIZE
ALTER INDEX ALL ON	POS	REORGANIZE
ALTER INDEX ALL ON	Dados_Diarios_Abre_Dia	REORGANIZE
ALTER INDEX ALL ON	Contas_Bancarias	REORGANIZE
ALTER INDEX ALL ON	Grid_Consignacoes	REORGANIZE
ALTER INDEX ALL ON	A_Fazer_Areas	REORGANIZE
ALTER INDEX ALL ON	MDFe_WebServices	REORGANIZE
ALTER INDEX ALL ON	Operacao_Grupo_Operacoes	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Fotos	REORGANIZE
ALTER INDEX ALL ON	Exporta_Web_Recibos_Mov	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_NVE	REORGANIZE
ALTER INDEX ALL ON	Whatsapp_Registro_Mensagens	REORGANIZE
ALTER INDEX ALL ON	Classes	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Contas_Historico	REORGANIZE
ALTER INDEX ALL ON	Ordens_Producao_Itens_Materia_Prima	REORGANIZE
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_Vale_Pedagio	REORGANIZE
ALTER INDEX ALL ON	Bridge_Filial	REORGANIZE
ALTER INDEX ALL ON	MobileSync_Registros_Recebidos	REORGANIZE
ALTER INDEX ALL ON	Parametros_Fiscal	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_Detalhe_Documentos_Fiscais	REORGANIZE
ALTER INDEX ALL ON	Fidelidade_Cli_For_Extrato	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Central_Controle	REORGANIZE
ALTER INDEX ALL ON	Unidades_Venda	REORGANIZE
ALTER INDEX ALL ON	Layout_Impressao_Linhas_Variaveis	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Formas_Recebimento_Pagamento_Cheques_Clientes_V2	REORGANIZE
ALTER INDEX ALL ON	Meta_Funcionario	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Promocao	REORGANIZE
ALTER INDEX ALL ON	Movimento_Link_Pagamento	REORGANIZE
ALTER INDEX ALL ON	Operacoes	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Formas_Recebimento_Pagamento_Lancamentos_Bancarios_V2	REORGANIZE
ALTER INDEX ALL ON	NFe_WebServices4	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_Consignacao	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv	REORGANIZE
ALTER INDEX ALL ON	Movimento_Cotacao_Compra	REORGANIZE
ALTER INDEX ALL ON	Moedas	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Central_Controle_Informacoes	REORGANIZE
ALTER INDEX ALL ON	Fidelidade_Pontos_Cli_For	REORGANIZE
ALTER INDEX ALL ON	Protestos	REORGANIZE
ALTER INDEX ALL ON	MDFe_Nao_Encerrados	REORGANIZE
ALTER INDEX ALL ON	Layout_Impressao_Campos	REORGANIZE
ALTER INDEX ALL ON	MobileSync_Operacoes	REORGANIZE
ALTER INDEX ALL ON	SAT_Compartilhado_Maquinas	REORGANIZE
ALTER INDEX ALL ON	Movimento_Entrega_Volumes_Lacres	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_DI_Adicao	REORGANIZE
ALTER INDEX ALL ON	Geral	REORGANIZE
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_Referenciados_V103	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Situacoes_OS	REORGANIZE
ALTER INDEX ALL ON	Encomendas	REORGANIZE
ALTER INDEX ALL ON	SAT_Compartilhado_Pedidos	REORGANIZE
ALTER INDEX ALL ON	Log_V2_Maquinas	REORGANIZE
ALTER INDEX ALL ON	Analise_Compras	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Central_Controle_Informacoes_Condicoes	REORGANIZE
ALTER INDEX ALL ON	Grupo_Cli_For	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Formas_Recebimento_Pagamento_V2	REORGANIZE
ALTER INDEX ALL ON	SAT_Compartilhado_Pedidos_Cancelamento	REORGANIZE
ALTER INDEX ALL ON	Grupos	REORGANIZE
ALTER INDEX ALL ON	Tamanhos	REORGANIZE
ALTER INDEX ALL ON	Ordens_Producao_Relacao_Movimento	REORGANIZE
ALTER INDEX ALL ON	Operacoes_Filiais	REORGANIZE
ALTER INDEX ALL ON	MDFe_Eventos	REORGANIZE
ALTER INDEX ALL ON	Analise_Compras_Movimentos_Gerados	REORGANIZE
ALTER INDEX ALL ON	Movimento_Transferencias_Importacoes	REORGANIZE
ALTER INDEX ALL ON	Estoque_Atual_Cli_For_Data_Alteracao	REORGANIZE
ALTER INDEX ALL ON	Documentos_Areas	REORGANIZE
ALTER INDEX ALL ON	Mensagem_Cidade_Estado	REORGANIZE
ALTER INDEX ALL ON	Promocoes_Especiais	REORGANIZE
ALTER INDEX ALL ON	Movimento_Cotacao_Compra_Fornecedores	REORGANIZE
ALTER INDEX ALL ON	Cli_For_Grupo_Cli_For	REORGANIZE
ALTER INDEX ALL ON	Enquadramento_IPI	REORGANIZE
ALTER INDEX ALL ON	NFCe_Contingencia_Automatica	REORGANIZE
ALTER INDEX ALL ON	Administradoras_Cartao_Filial_Conta	REORGANIZE
ALTER INDEX ALL ON	Codigo_ANP	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Edicao	REORGANIZE
ALTER INDEX ALL ON	Contagem_Estoque	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_DI	REORGANIZE
ALTER INDEX ALL ON	Movimento_VEF_Lock	REORGANIZE
ALTER INDEX ALL ON	NFCe_Contingencia_Automatica_Mensagem_Operador	REORGANIZE
ALTER INDEX ALL ON	Contas_Bancarias_Funcionarios	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Sangria_Historico	REORGANIZE
ALTER INDEX ALL ON	Licencas	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_Devolucao_Simplificada	REORGANIZE
ALTER INDEX ALL ON	Movimento_Cotacao_Compra_Prod_Serv	REORGANIZE
ALTER INDEX ALL ON	Bridge_Calendario	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Similares	REORGANIZE
ALTER INDEX ALL ON	Transporte_Transportadora	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Divisao_Cli_For_Plano_Pagamento	REORGANIZE
ALTER INDEX ALL ON	Parametros_SAT	REORGANIZE
ALTER INDEX ALL ON	Carga_Tributaria_Estados	REORGANIZE
ALTER INDEX ALL ON	Administradoras_Cartao	REORGANIZE
ALTER INDEX ALL ON	Movimento_Entrega_Motivo	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Lote	REORGANIZE
ALTER INDEX ALL ON	Avisos_Temporarios_Funcionarios	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_Quantidade_Entregue	REORGANIZE
ALTER INDEX ALL ON	Integrador_Evencard_Vendas_Exportadas	REORGANIZE
ALTER INDEX ALL ON	Movimento_Reserva	REORGANIZE
ALTER INDEX ALL ON	Motivo_Desefetivacao	REORGANIZE
ALTER INDEX ALL ON	Emails_Enviados	REORGANIZE
ALTER INDEX ALL ON	Cotacoes	REORGANIZE
ALTER INDEX ALL ON	Ultimos_Acessos	REORGANIZE
ALTER INDEX ALL ON	Grupos_Funcionarios	REORGANIZE
ALTER INDEX ALL ON	Fila_MFe	REORGANIZE
ALTER INDEX ALL ON	Bridge_Controle_Importacao_Movimentacoes	REORGANIZE
ALTER INDEX ALL ON	Movimento_Entrada_Transferencia_Automatica	REORGANIZE
ALTER INDEX ALL ON	Tabelas_Preco_Cli_For_Classes	REORGANIZE
ALTER INDEX ALL ON	Promocoes_Especiais_Filiais	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Icms_Partilha_Relacao	REORGANIZE
ALTER INDEX ALL ON	Promocoes_Especiais_Prod_Serv	REORGANIZE
ALTER INDEX ALL ON	Controle_Versoes	REORGANIZE
ALTER INDEX ALL ON	Meios_Pagamento_PAF_NFCe	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Grade	REORGANIZE
ALTER INDEX ALL ON	Campos_Imprimir_Preco	REORGANIZE
ALTER INDEX ALL ON	Log_SAT	REORGANIZE
ALTER INDEX ALL ON	Movimento_Checkout	REORGANIZE
ALTER INDEX ALL ON	Recentes	REORGANIZE
ALTER INDEX ALL ON	Luxottica_Sequencia	REORGANIZE
ALTER INDEX ALL ON	Funcionarios	REORGANIZE
ALTER INDEX ALL ON	Registro_Maquinas	REORGANIZE
ALTER INDEX ALL ON	NBS	REORGANIZE
ALTER INDEX ALL ON	Contas_Bancarias_Lock	REORGANIZE
ALTER INDEX ALL ON	AutoSync_Modulos	REORGANIZE
ALTER INDEX ALL ON	Log_Fila_MFe	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Customizavel	REORGANIZE
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_Inutilizados	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Carga_Tributaria	REORGANIZE
ALTER INDEX ALL ON	Z_IdealSoft	REORGANIZE
ALTER INDEX ALL ON	Registro_Acoes	REORGANIZE
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_UF_Percurso	REORGANIZE
ALTER INDEX ALL ON	NCM_Sistema	REORGANIZE
ALTER INDEX ALL ON	Subclasses	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Formas_Recebimento_Pagamento_Contas_V2	REORGANIZE
ALTER INDEX ALL ON	Luxottica_Codigos_Filiais	REORGANIZE
ALTER INDEX ALL ON	Chat_Mensagens	REORGANIZE
ALTER INDEX ALL ON	Plano_Contas2	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_Promocoes_Especiais	REORGANIZE
ALTER INDEX ALL ON	Mensagens	REORGANIZE
ALTER INDEX ALL ON	Familias	REORGANIZE
ALTER INDEX ALL ON	Mensagens_Funcionarios	REORGANIZE
ALTER INDEX ALL ON	Agenda	REORGANIZE
ALTER INDEX ALL ON	Caixas_Movimentacao_Lock	REORGANIZE
ALTER INDEX ALL ON	Contagem_Estoque_Itens_Lotes	REORGANIZE
ALTER INDEX ALL ON	NFe_Prorrogacao	REORGANIZE
ALTER INDEX ALL ON	Contas_Contabeis	REORGANIZE
ALTER INDEX ALL ON	Caixas_Funcionarios_Relatorio	REORGANIZE
ALTER INDEX ALL ON	Cli_For_Documentos_Autorizados_XML	REORGANIZE
ALTER INDEX ALL ON	Bridge_Calendario_Detalhe	REORGANIZE
ALTER INDEX ALL ON	Grupos_Mala	REORGANIZE
ALTER INDEX ALL ON	Luxottica_Movimento_Exportado	REORGANIZE
ALTER INDEX ALL ON	Boletos_Liberacao	REORGANIZE
ALTER INDEX ALL ON	Contas_Contabeis_Filiais	REORGANIZE
ALTER INDEX ALL ON	Noticias_Personalizadas	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Email_Layout	REORGANIZE
ALTER INDEX ALL ON	Identificadores_Pagamento_MFe	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Customizavel_Registro	REORGANIZE
ALTER INDEX ALL ON	Movimento_DAV	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Fotos	REORGANIZE
ALTER INDEX ALL ON	Mala_Direta	REORGANIZE
ALTER INDEX ALL ON	NCM	REORGANIZE
ALTER INDEX ALL ON	Contagem_Estoque_Itens_Series	REORGANIZE
ALTER INDEX ALL ON	Usuarios_Ativos	REORGANIZE
ALTER INDEX ALL ON	Noticias_Personalizadas_Filiais	REORGANIZE
ALTER INDEX ALL ON	Layout_Impressao_Linhas_Etiqueta	REORGANIZE
ALTER INDEX ALL ON	Motivo_Desconto	REORGANIZE
ALTER INDEX ALL ON	MobileSync_Funcionarios_Regiao	REORGANIZE
ALTER INDEX ALL ON	Plano_Contas3	REORGANIZE
ALTER INDEX ALL ON	Movimento_Origem	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Filiais_Permitido	REORGANIZE
ALTER INDEX ALL ON	Noticias_Personalizadas_Funcionarios_Lidos	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Maquina	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_Troca	REORGANIZE
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais_MDFe_Lacres	REORGANIZE
ALTER INDEX ALL ON	Movimento_Documentos_Fiscais	REORGANIZE
ALTER INDEX ALL ON	Grupos_Filiais_MobileView	REORGANIZE
ALTER INDEX ALL ON	Compromissos_Grupos	REORGANIZE
ALTER INDEX ALL ON	Cli_For_Limite_Credito	REORGANIZE
ALTER INDEX ALL ON	Frete	REORGANIZE
ALTER INDEX ALL ON	Estoque_Atual_Lote	REORGANIZE
ALTER INDEX ALL ON	Entrega_Transportes	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Filiais_Restrito	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Senha_Avancada	REORGANIZE
ALTER INDEX ALL ON	Caixas_Funcionarios_Fazer_Venda	REORGANIZE
ALTER INDEX ALL ON	Campanhas	REORGANIZE
ALTER INDEX ALL ON	Recibos_Descricao	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Customizavel_Titulo	REORGANIZE
ALTER INDEX ALL ON	Otica_Laboratorios	REORGANIZE
ALTER INDEX ALL ON	Classificacao_Abc	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Conf	REORGANIZE
ALTER INDEX ALL ON	Cli_For_Contatos_Efetuados	REORGANIZE
ALTER INDEX ALL ON	Fabricantes	REORGANIZE
ALTER INDEX ALL ON	sysdiagrams	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Filtros	REORGANIZE
ALTER INDEX ALL ON	Movimento_Dados_NFSe	REORGANIZE
ALTER INDEX ALL ON	NFe_Prorrogacao_Eventos	REORGANIZE
ALTER INDEX ALL ON	Filiais_MobileView	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_Troca_Utilizadas	REORGANIZE
ALTER INDEX ALL ON	Meta_Venda	REORGANIZE
ALTER INDEX ALL ON	Otica_Status	REORGANIZE
ALTER INDEX ALL ON	Scanntech_Fechamento_Diario_Exportado	REORGANIZE
ALTER INDEX ALL ON	Grupos_Passos_Cobranca	REORGANIZE
ALTER INDEX ALL ON	Movimento_Saida_Transferencia_Automatica	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Caixa_Grupo	REORGANIZE
ALTER INDEX ALL ON	Estoque_Atual_Cli_For	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Grupos	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Contas_MobileView	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Contas	REORGANIZE
ALTER INDEX ALL ON	Caixas_Funcionarios_Desfazer_Venda	REORGANIZE
ALTER INDEX ALL ON	Plano_Contas1	REORGANIZE
ALTER INDEX ALL ON	NVE	REORGANIZE
ALTER INDEX ALL ON	Sync_Contra_Senha_Geradas	REORGANIZE
ALTER INDEX ALL ON	Remarcacao_Precos	REORGANIZE
ALTER INDEX ALL ON	Estoque_Atual_Serie	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Nat_Rec	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_MobileView	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_Troca_Origem	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Operacoes_Entrada	REORGANIZE
ALTER INDEX ALL ON	Imagens_Telas	REORGANIZE
ALTER INDEX ALL ON	Cli_For_Mobile_Sync	REORGANIZE
ALTER INDEX ALL ON	Transporte_Proprio	REORGANIZE
ALTER INDEX ALL ON	Agenda_Areas	REORGANIZE
ALTER INDEX ALL ON	MobileView_Filiais	REORGANIZE
ALTER INDEX ALL ON	Cli_For	REORGANIZE
ALTER INDEX ALL ON	Movimento_Financeiro	REORGANIZE
ALTER INDEX ALL ON	Caixas	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Caixas_Padrao	REORGANIZE
ALTER INDEX ALL ON	Contas_Consumo	REORGANIZE
ALTER INDEX ALL ON	Noticias_Personalizadas_MobileView	REORGANIZE
ALTER INDEX ALL ON	Classes_MobileView	REORGANIZE
ALTER INDEX ALL ON	Caixas_Funcionarios_Movimento	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Operacoes_Saida	REORGANIZE
ALTER INDEX ALL ON	Financeiro_Cobranca_Passos	REORGANIZE
ALTER INDEX ALL ON	Vendedor_Interno_Usuarios_Logados	REORGANIZE
ALTER INDEX ALL ON	Movimento_MobileView	REORGANIZE
ALTER INDEX ALL ON	Ordens_Producao_Insumos_Consumidos	REORGANIZE
ALTER INDEX ALL ON	Grupo_Remarcacao_Precos	REORGANIZE
ALTER INDEX ALL ON	NFe_Prorrogacao_Itens	REORGANIZE
ALTER INDEX ALL ON	Grupos_Filiais	REORGANIZE
ALTER INDEX ALL ON	Subclasses_MobileView	REORGANIZE
ALTER INDEX ALL ON	Transporte_Proprio_Condutores	REORGANIZE
ALTER INDEX ALL ON	Segurancas	REORGANIZE
ALTER INDEX ALL ON	Movimento_Prod_Serv_MobileView	REORGANIZE
ALTER INDEX ALL ON	Ordens_Producao_Itens_Produzidos	REORGANIZE
ALTER INDEX ALL ON	Estoque_Atual	REORGANIZE
ALTER INDEX ALL ON	Scanntech_Fechamento_Promocao_Exportado	REORGANIZE
ALTER INDEX ALL ON	Info_Sync	REORGANIZE
ALTER INDEX ALL ON	Campanhas_Itens	REORGANIZE
ALTER INDEX ALL ON	Credito_Cli_For_Movimento_Atrelado	REORGANIZE
ALTER INDEX ALL ON	Grupos_MobileView	REORGANIZE
ALTER INDEX ALL ON	Movimento_Mobile_Sync	REORGANIZE
ALTER INDEX ALL ON	Movimento_Entrega	REORGANIZE
ALTER INDEX ALL ON	Filiais_Certificados	REORGANIZE
ALTER INDEX ALL ON	Motivo_Devolucao	REORGANIZE
ALTER INDEX ALL ON	Recibos	REORGANIZE
ALTER INDEX ALL ON	Compromissos	REORGANIZE
ALTER INDEX ALL ON	CFOP	REORGANIZE
ALTER INDEX ALL ON	Agenda_Contatos	REORGANIZE
ALTER INDEX ALL ON	Antecipacao_Financeira_Historico	REORGANIZE
ALTER INDEX ALL ON	Familias_MobileView	REORGANIZE
ALTER INDEX ALL ON	Configuracoes_Email	REORGANIZE
ALTER INDEX ALL ON	Parametros_Scanntech	REORGANIZE
ALTER INDEX ALL ON	Filiais_CFOP_Ignorar_Custo	REORGANIZE
ALTER INDEX ALL ON	Funcionarios_Historico	REORGANIZE
ALTER INDEX ALL ON	Caixas_Funcionarios_Transferencia	REORGANIZE
ALTER INDEX ALL ON	Grupo_Remarcacao_Precos_Regras	REORGANIZE
ALTER INDEX ALL ON	Filiais_Grupos_Filiais	REORGANIZE
ALTER INDEX ALL ON	Prod_Serv_Precos	REORGANIZE
ALTER INDEX ALL ON	Estoque_Atual_MobileView	REORGANIZE
